### ISSUE TITLE
pydoclint raises AttributeError on class with a Union type

### ISSUE THREAD

**Issue by neilo-df** [jsh9/pydoclint#135]
Using python 3.11 and pydoclint 0.5.0

pydoclint raises `AttributeError: 'BinOp' object has no attribute 'id'` on the following file:
```
from dataclasses import dataclass

@dataclass
class foo:
    bar: str | int
```

And in fact it doesn't need to be a dataclass at all
```
class foo:
    bar: str | int
```

Whereas pydoclint 0.4.0 processes either of these examples without any exception.

It doesn't seem to matter what the type union is.  In our code, what caused the error was an optional, more like

```
class foo:
    bar: str | None = None
```

**Comment by shinnosukeono** [comment]
I could reproduce the above error with Python 3.10, flake8 7.1.0, and pydoclint 0.5.0. Also, it raises another type of error `AttributeError: 'Subscript' object has no attribute 'id'` (full message attached below), which I confirmed doesn't appear with pydoclint 0.4.1, on the following code:
```
from typing import Optional

from attr import attrib, attrs


@attrs()
class User:
    name: str = attrib()
    age: int = attrib()
    occupation: Optional[str] = attrib(default=None)

```

Complete error message:
```
Traceback (most recent call last):
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/site-packages/flake8/main/application.py", line 187, in _run
    self.run_checks()
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/site-packages/flake8/main/application.py", line 103, in run_checks
    self.file_checker_manager.run()
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/site-packages/flake8/checker.py", line 238, in run
    self.run_serial()
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/site-packages/flake8/checker.py", line 216, in run_serial
    self.results = [
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/site-packages/flake8/checker.py", line 221, in <listcomp>
    ).run_checks()
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/site-packages/flake8/checker.py", line 526, in run_checks
    self.run_ast_checks()
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/site-packages/flake8/checker.py", line 428, in run_ast_checks
    for line_number, offset, text, _ in runner:
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/site-packages/pydoclint/flake8_entry.py", line 290, in run
    v.visit(self._tree)
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/ast.py", line 418, in generic_visit
    self.visit(item)
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/site-packages/pydoclint/visitor.py", line 91, in visit_ClassDef
    checkClassAttributesAgainstClassDocstring(
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/site-packages/pydoclint/utils/visitor_helper.py", line 39, in checkClassAttributesAgainstClassDocstring
    actualArgs: ArgList = _convertClassAttributesIntoArgList(classAttributes)
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/site-packages/pydoclint/utils/visitor_helper.py", line 96, in _convertClassAttributesIntoArgList
    atl.append(Arg.fromAstAnnAssign(attr))
  File "/Users/shinnosukeono/miniforge3/envs/flake8-test/lib/python3.10/site-packages/pydoclint/utils/arg.py", line 115, in fromAstAnnAssign
    typeHint=astAnnAssign.annotation.id,
AttributeError: 'Subscript' object has no attribute 'id'
```

**Comment by jsh9** [comment]
Hi, thank you both for testing it.

It's a bug that I introduced in 0.5.1.  I have fixed it and published a new version, 0.5.1.  Please check it out.

Btw, 0.5.0 and 0.5.1 is meant to introduce a new functionality: checking class attributes.

Your examples (after I fixed the bug) may trigger new violations related to class attributes.  If you don't need to check class attributes, you can turn it off via this config option: https://jsh9.github.io/pydoclint/config_options.html#14---check-class-attributes-shortform--cca-default-true

**Comment by shinnosukeono** [comment]
Hi, I tried it out and confirmed the error was resolved. Thank you for your great work!

**Comment by jsh9** [comment]
I'm glad the new version works for you!
