### ISSUE TITLE
ImportError: cannot import name 'DocstringAttr' from 'docstring_parser.common'

### ISSUE THREAD

**Issue by magnussommarsjo** [jsh9/pydoclint#162]
From time to time I run into the following issue
```bash
$ pydoclint .
Traceback (most recent call last):
  File "/home/mlengqui/miniconda3/envs/sohvida_dc_update/bin/pydoclint", line 5, in <module>
    from pydoclint.main import main
  File "/home/mlengqui/miniconda3/envs/sohvida_dc_update/lib/python3.9/site-packages/pydoclint/main.py", line 18, in <module>
    from pydoclint.visitor import Visitor
  File "/home/mlengqui/miniconda3/envs/sohvida_dc_update/lib/python3.9/site-packages/pydoclint/visitor.py", line 5, in <module>
    from pydoclint.utils.arg import Arg, ArgList
  File "/home/mlengqui/miniconda3/envs/sohvida_dc_update/lib/python3.9/site-packages/pydoclint/utils/arg.py", line 4, in <module>
    from docstring_parser.common import DocstringAttr, DocstringParam
ImportError: cannot import name 'DocstringAttr' from 'docstring_parser.common' (/home/mlengqui/miniconda3/envs/sohvida_dc_update/lib/python3.9/site-packages/docstring_parser/common.py)
```
This is even though I have the `docstring_parser_fork` installed.
```bash
$ pip list | grep docstring_parser
docstring_parser           0.16
docstring_parser_fork      0.0.9
```

Is this due to that pydoclint is using the 'regular' version instead of the fork in this case?

**Comment by jsh9** [comment]
Hi @magnussommarsjo , maybe it's best to uninstall `docstring_parser` to avoid naming conflicts.  I added `DocstringAttr` in the fork, but apparently your Python was still looking into the original "docstring_parser" library.

**Comment by magnussommarsjo** [comment]
Removing by simply `pip uninstall docstring-parser` will then give an `ModuleNotFoundError: No module named 'docstring_parser.common'` when running `pydoclint .`.

Why I ending up with both is that I have another dependency on `docstring-parser` called `kfp`. Below is the "inverted" dependency graph. 
```
docstring-parser v0.16
└── kfp v1.8.22 (*)
docstring-parser-fork v0.0.9
└── pydoclint v0.5.8
    ├── my-project
```

**Comment by magnussommarsjo** [comment]
Here is a minimal code sample that will recreate this issue using conda. 
```bash
conda create -n testenv python=3.9 -y
conda activate testenv
pip install kfp pydoclint
pydoclint .
```

**Comment by jsh9** [comment]
Could you run pydoclint in a separate environment?

My earlier suggestion to uninstall `docstring_parser` wouldn't work, because it turned out that both `docstring_parser` and `docstring_parser_fork` were installed in the same folder: `/Users/...../anaconda3/envs/testenv/lib/python3.9/site-packages/docstring_parser/*`, because they share the same module name, which is `docstring_parser`.

There is unfortunately not a perfect fix for this situation.  I prefer not to change the module name of the forked library (otherwise keeping up with the latest changes on the original repo would be difficult).  I also couldn't get bug fixes to be merged in the original repo (which is why I had to fork it).

**Comment by magnussommarsjo** [comment]
Well I can run it in another environment. But that is not a great workflow for me or my team. This would basically mean that as soon as I need to commit and run "pre-commit" where my linting checks are run. I'll then need to temporarily  switch environment and then back again when I need to run testing with pytest. 

I understand that this issue might be hard to fix. But anyhow I wanted to raise it so that you are aware of it. 😉

**Comment by jsh9** [comment]
May I see your tox or pre-commit config? I've always been running pydoclint in a dedicated env in `tox`, so I never ran into this issue before.

And btw I just found a workaround:

```
conda create -n testenv python=3.9 -y
conda activate testenv
pip install kfp
pip install pydoclint
pydoclint .
```

The key is to split up `kfp` and `pydoclint` into 2 commands, and **make sure you install `pydoclint` last** so that the old (original) `docstring_parser` gets overwritten by `docstring_parser_fork`.  You can inspect the file `.../anaconda3/envs/testenv/lib/python3.9/site-packages/docstring_parser/common.py` to double check: the forked version [has 298 lines](https://github.com/jsh9/docstring_parser_fork/blame/80489b009141c5bd75822977004de524238870d7/docstring_parser/common.py) while the original version [has 228 lines](https://github.com/rr-/docstring_parser/blob/4951137875e79b438d52a18ac971ec0c28ef269c/docstring_parser/common.py).

**Comment by zephyr5050** [comment]
I'm facing the same issue for a similar reason. I'm using the [`jsonargparse`](https://jsonargparse.readthedocs.io/en/stable) package with the `signatures` optional feature. This feature installs `docstring-parser` v0.16. I manage my environment using `uv`. In my case, both `docstring-parser` and `docstring-parser-fork` are installed in my environment, but since `docstring-parser-fork` is imported with the same name as `docstring-parser`, pydoclint attempts to use `docstring-parser`, causing the error above.

As echo'd by @magnussommarsjo [above](https://github.com/jsh9/pydoclint/issues/162#issuecomment-2384966261), running pydoclint in it's own environment is not a great workflow since we just install and run all tools (including pydoclint) in the same environment.

**Comment by jsh9** [comment]
Hi @zephyr5050, @gmendozaseekr, and @magnussommarsjo , could you help me understand why running pydoclint in a separate env is not feasible or inconvenient?

If you can show me your tox or pre-commit config file, maybe we can design some workarounds.

I'm not intentionally blocking this, but renaming docstring_parser makes it much harder to keep up with the upstream (i.e., the original repo) in the future, which isn't the most ideal for the maintainability of pydoclint.

**Comment by jsh9** [comment]
I didn't expect people to include pydoclint as their project's dependencies, because pydoclint is designed to be a standalone command line tool, not a library.  (You can't "import pydoclint" in Python because importing it does nothing.)

I can show you an example of how my other project uses pydoclint.  This is the tox.ini file: https://github.com/Caltech-geoquake/PySeismoSoil/blob/8891defcecdde27e05238d367361a06d06124394/tox.ini#L70-L75

There's a "pydoclint" testing environment that only does pydoclint linting.

**Comment by magnussommarsjo** [comment]
For me, my collegues and many others in my company its quite common to simple have all project dependencies together with application dependencies in one file (example below with `pyproject.toml` and `uv`). Then we simply execute these manually, with pre-commit or later via Github actions.  This is a very lightweight and easy to understand setup for developers.

```
───────┬──────────────────────────────────────────────────────────────────────────
       │ File: pyproject.toml
───────┼──────────────────────────────────────────────────────────────────────────
   1   │ [project]
   2   │ name = "sample-project"
   3   │ version = "0.1.0"
   4   │ description = "Add your description here"
   5   │ readme = "README.md"
   6   │ requires-python = ">=3.10"
   7   │ dependencies = [
   8   │     "kfp==1.8.22",
   9   │ ]
  10   │ 
  11   │ [dependency-groups]
  12   │ dev = [
  13   │     "pre-commit>=4.3.0",
  14   │     "pydoclint>=0.6.10",
  15   │     "pytest>=8.4.1",
  16   │     "ruff>=0.12.9",
  17   │ ]

```

I see that using tox can resolve these dependency issues and is a valid workaround. What worries me is the following:
- Increase project complexity by introducing tox
- Slower execution at commit (me guessing here since you have to run from multiple different environments)

I guess that you would then execute pydoclint indirectly with pre-commit via tox?

**Comment by magnussommarsjo** [comment]
> If you use pre-commit, it's even easier to isolate pydoclint from the other dependencies. Because each hook in pre-commit is an isolated environment.
> 
> You can remove `"pydoclint>=0.6.10"` from your pyproject.toml, and add pydoclint hook to your `.pre-commit-config.yaml`. Here's an example for you (specific to my other project):
> 
>   - repo: https://github.com/jsh9/pydoclint
>     rev: 0.6.10
>     hooks:
>       - id: pydoclint
>         args: [--style=numpy]
>         exclude: '\.git|.?venv|\.tox'
>         files: ^PySeismoSoil/
> (You don't need tox at all.)
> 
> Both tox and pre-commit are built on the philosophy of isolated testing environments. This is always recommended over mixing different dependencies.
> 
> Today you are facing pydoclint issues because of a package name clash (I admit it's because I forked docstring_parser), but in the future you may encounter even more dependency clashes from other sources. The only clash-proof way is to isolate different tools in their own environments.

I somehow thought that I needed the packages installed in my regular environment to make them work in pre-commit🤦‍♂️. This definitely solves my issues!  😄 Thanks for the clarification.

**Comment by gmendozaseekr** [comment]
@jsh9 In my case, we utilize pydoclint in a bit unconventional way. Our implementation involves an endpoint that validates custom python code and in the process utilizes pydoclint via subprocess. We currently bundle the dependency in our pyproject.toml. One workaround I found was forcing the fork to get installed last as you mention above but I am concerned that eventually that will break something for other dependancies are now forced to rely on the fork. Not sure if theres a better approach that could get me closer to what you are suggesting but was curious if others had a found a workaround to avoid the potential extra work involved with that
